### ISSUE TITLE
v1.9.1 preview 1 - Default Function color should be orange

### ISSUE THREAD

**Issue by BOXOPHOBIC** [AmplifyCreations/AmplifyShaderEditor-Feedback#121] opened 2022-10-24 06:42 UTC
I think the function's default color should be orange as before. The new color blends in too much with the rest of the graph + orange for functions and switches related to functions makes sense. Before / After

![image](https://user-images.githubusercontent.com/33637574/197463416-5fc770dc-ccda-4839-b92b-940ae0d951f3.png)

![image](https://user-images.githubusercontent.com/33637574/197463432-e5d4ec46-fd6b-4fe7-abd3-e9ff670ecd85.png)

**Comment by diogovtx** [comment] 2022-10-24 17:03
we need to talk about this though, because this is exactly what was intended
the thing is, it's much easier and quicker to expand ASE functionality without making scripting-based nodes, and just using shader functions, and we need to move FAST

however, maybe there's a compromise we can find here, for example, keeping functionality for most SFs and adding an toggle/option to colorize based on category => in this case I'd just toggle all the existing ASE built-in SFs with this option, but it'd be off by default on existing and new ones; defined on a per-SF basis, like color overrid

**Comment by diogovtx** [comment] 2022-10-24 17:43
OK as agreed, let's do 3 options on a per SF basis:
1. always orange (default)
2. follows category colors
3. custom color

**Comment by diogovtx** [comment] 2022-10-24 22:09
Fixed. Closing

**Closed by diogovtx** 2022-10-24 22:09 UTC
Labels: high priority
